# Copyright (c) 2012-2019 Robin Degen

if (NOT TARGET GLAD::GLAD)
    add_library(GLAD::GLAD STATIC IMPORTED)
    set_target_properties(GLAD::GLAD PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include")

    set_property(TARGET GLAD::GLAD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(GLAD::GLAD PROPERTIES IMPORTED_LOCATION_RELEASE "${CMAKE_CURRENT_LIST_DIR}/lib/glad.lib")

    set_property(TARGET GLAD::GLAD APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(GLAD::GLAD PROPERTIES IMPORTED_LOCATION_DEBUG "${CMAKE_CURRENT_LIST_DIR}/lib/gladd.lib")
endif ()
